@BASE_URL = http://localhost:3333

###

# @name create_account
POST {{BASE_URL}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "john_doe"
}

###

# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "name": "John Doe",
  "password": "john_doe"
}