@BASE_URL = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

###

# @name create_account
POST {{BASE_URL}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "john_doe"
}

###

# @name authenticate
POST {{BASE_URL}}/sessions
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "john_doe"
}

###

# @name create_question
POST {{BASE_URL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "New question 3",
  "content": "Question content"
}

###

# @name create_question_without_token
POST {{BASE_URL}}/questions
Content-Type: application/json

{
  "title": "New question 3",
  "content": "Question content"
}

###

# @name fetch_recent_questions
GET {{BASE_URL}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}} 

###

# @name fetch_recent_questions_without_token
GET {{BASE_URL}}/questions?page=1
Content-Type: application/json
